let states = [
  {
    abbr: "AK",
    name: "Alaska",
    capital: "Juneau",
    img_position: "-105px 0px;",
  },
  {
    abbr: "AL",
    name: "Alabama",
    capital: "Montgomery",
    img_position: "-5px 0px;",
  },

  {
    abbr: "AZ",
    name: "Arizona",
    capital: "Phoenix",
    img_position: "-205px 0px;",
  },
  {
    abbr: "AR",
    name: "Arkansas",
    capital: "Little Rock",
    img_position: "-310px 0px;",
  },
  {
    abbr: "CA",
    name: "California",
    capital: "Sacramento",
    img_position: "-410px 0px;",
  },
  {
    abbr: "CO",
    name: "Colorado",
    capital: "Denver",
    img_position: "-0px -100px;",
  },
  {
    abbr: "CT",
    name: "Connecticut",
    capital: "Hartford",
    img_position: "-100px -100px;",
  },
  {
    abbr: "DE",
    name: "Delaware",
    capital: "Dover",
    img_position: "-215px -100px;",
  },
  {
    abbr: "FL",
    name: "Florida",
    capital: "Tallahassee",
    img_position: "-315px -100px;",
  },
  {
    abbr: "GA",
    name: "Georgia",
    capital: "Atlanta",
    img_position: "-430px -100px;",
  },
  {
    abbr: "HI",
    name: "Hawaii",
    capital: "Honolulu",
    img_position: "-0px -200px;",
  },
  {
    abbr: "ID",
    name: "Idaho",
    capital: "Boise",
    img_position: "-5px 0px",
  },
  {
    abbr: "IL",
    name: "Illinois",
    capital: "Springfield",
    img_position: "-5px 0px",
  },
  {
    abbr: "IN",
    name: "Indiana",
    capital: "Indianapolis",
    img_position: "-5px 0px",
  },
  {
    abbr: "IA",
    name: "Iowa",
    capital: "Des Moines",
    img_position: "-5px 0px",
  },
  {
    abbr: "KS",
    name: "Kansas",
    capital: "Topeka",
    img_position: "-5px 0px",
  },
  {
    abbr: "KY",
    name: "Kentucky",
    capital: "Frankfort",
    img_position: "-5px 0px",
  },
  {
    abbr: "LA",
    name: "Louisiana",
    capital: "Baton Rouge",
    img_position: "-5px 0px",
  },
  {
    abbr: "ME",
    name: "Maine",
    capital: "Augusta",
    img_position: "-5px 0px",
  },
  {
    abbr: "MD",
    name: "Maryland",
    capital: "Annapolis",
    img_position: "-5px 0px",
  },
  {
    abbr: "MA",
    name: "Massachusetts",
    capital: "Boston",
    img_position: "-5px 0px",
  },
  {
    abbr: "MI",
    name: "Michigan",
    capital: "Lansing",
    img_position: "-5px 0px",
  },
  {
    abbr: "MN",
    name: "Minnesota",
    capital: "Saint Paul",
    img_position: "-5px 0px",
  },
  {
    abbr: "MS",
    name: "Mississippi",
    capital: "Jackson",
    img_position: "-5px 0px",
  },
  {
    abbr: "MO",
    name: "Missouri",
    capital: "Jefferson City",
    img_position: "-5px 0px",
  },
];
